[[releases]]
range = "v0.8"
end_of_life = "2014-07-31"

[releases.metadata]
start = "2012-06-25"

[[releases]]
range = "v0.10"
end_of_life = "2016-10-31"

[releases.metadata]
start = "2013-03-11"

[[releases]]
range = "v0.12"
end_of_life = "2016-12-31"

[releases.metadata]
start = "2015-02-06"

[[releases]]
range = "v4"
end_of_life = "2018-04-30"

[releases.metadata]
start = "2015-09-08"
lts = "2015-10-12"
maintenance = "2017-04-01"

[[releases]]
range = "v5"
end_of_life = "2016-06-30"

[releases.metadata]
start = "2015-10-29"
maintenance = "2016-04-30"

[[releases]]
range = "v6"
end_of_life = "2019-04-30"

[releases.metadata]
start = "2016-04-26"
lts = "2016-10-18"
maintenance = "2018-04-30"

[[releases]]
range = "v7"
end_of_life = "2017-06-30"

[releases.metadata]
start = "2016-10-25"
maintenance = "2017-04-30"

[[releases]]
range = "v8"
end_of_life = "2019-12-31"

[releases.metadata]
start = "2017-05-30"
lts = "2017-10-31"
maintenance = "2019-01-01"

[[releases]]
range = "v9"
end_of_life = "2018-06-30"

[releases.metadata]
start = "2017-10-01"
maintenance = "2018-04-01"

[[releases]]
range = "v10"
end_of_life = "2021-04-30"

[releases.metadata]
start = "2018-04-24"
lts = "2018-10-30"
maintenance = "2020-05-19"

[[releases]]
range = "v11"
end_of_life = "2019-06-01"

[releases.metadata]
start = "2018-10-23"
maintenance = "2019-04-22"

[[releases]]
range = "v12"
end_of_life = "2022-04-30"

[releases.metadata]
start = "2019-04-23"
lts = "2019-10-21"
maintenance = "2020-11-30"

[[releases]]
range = "v13"
end_of_life = "2020-06-01"

[releases.metadata]
start = "2019-10-22"
maintenance = "2020-04-01"

[[releases]]
range = "v14"
end_of_life = "2023-04-30"

[releases.metadata]
start = "2020-04-21"
lts = "2020-10-27"
maintenance = "2021-10-19"

[[releases]]
range = "v15"
end_of_life = "2021-06-01"

[releases.metadata]
start = "2020-10-20"
maintenance = "2021-04-01"

[[releases]]
range = "v16"
end_of_life = "2023-09-11"

[releases.metadata]
start = "2021-04-20"
lts = "2021-10-26"
maintenance = "2022-10-18"

[[releases]]
range = "v17"
end_of_life = "2022-06-01"

[releases.metadata]
start = "2021-10-19"
maintenance = "2022-04-01"

[[releases]]
range = "v18"
end_of_life = "2025-04-30"

[releases.metadata]
start = "2022-04-19"
lts = "2022-10-25"
maintenance = "2023-10-18"

[[releases]]
range = "v19"
end_of_life = "2023-06-01"

[releases.metadata]
start = "2022-10-18"
maintenance = "2023-04-01"

[[releases]]
range = "v20"
end_of_life = "2026-04-30"

[releases.metadata]
start = "2023-04-18"
lts = "2023-10-24"
maintenance = "2024-10-22"

[[releases]]
range = "v21"
end_of_life = "2024-06-01"

[releases.metadata]
start = "2023-10-17"
maintenance = "2024-04-01"

[[releases]]
range = "v22"
end_of_life = "2027-04-30"

[releases.metadata]
start = "2024-04-24"
lts = "2024-10-29"
maintenance = "2025-10-21"

[[releases]]
range = "v23"
end_of_life = "2025-06-01"

[releases.metadata]
start = "2024-10-16"
maintenance = "2025-04-01"

[[releases]]
range = "v24"
end_of_life = "2028-04-30"

[releases.metadata]
start = "2025-05-06"
lts = "2025-10-28"
maintenance = "2026-10-20"

[[releases]]
range = "v25"
end_of_life = "2026-06-01"

[releases.metadata]
start = "2025-10-15"
maintenance = "2026-04-01"

[[releases]]
range = "v26"
end_of_life = "2029-04-30"

[releases.metadata]
start = "2026-04-22"
lts = "2026-10-28"
maintenance = "2027-10-20"
