name = "npm"

[[releases]]
version = "10.0.0"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v10.0.0.tar.gz"
etag = "76deb9389081c39e579893229d5eae52"

[[releases]]
version = "10.1.0"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v10.1.0.tar.gz"
etag = "0349d02bce8d37dc140532bf430759da"

[[releases]]
version = "10.2.0"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v10.2.0.tar.gz"
etag = "dda9858dd5e9ce23882acb9835dd1966"

[[releases]]
version = "10.2.1"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v10.2.1.tar.gz"
etag = "3bbb28e6c9d5af09cda308da77192603"

[[releases]]
version = "10.2.2"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v10.2.2.tar.gz"
etag = "012f28947b341bd567becf8c0898504c"

[[releases]]
version = "10.2.3"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v10.2.3.tar.gz"
etag = "4c179b74475886962ab2410d405c129a"

[[releases]]
version = "10.2.4"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v10.2.4.tar.gz"
etag = "ba18ad02ae207f876573075e493b4f03"

[[releases]]
version = "10.2.5"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v10.2.5.tar.gz"
etag = "614a9fdeda3870dd3b8fe416c5f52dd4"

[[releases]]
version = "10.3.0"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v10.3.0.tar.gz"
etag = "6005548b74556cb7eca593d60460d105"

[[releases]]
version = "10.4.0"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v10.4.0.tar.gz"
etag = "a859a224a5549630fe1907743c778eac"

[[releases]]
version = "10.5.0"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v10.5.0.tar.gz"
etag = "a5fe0f3135e3f65cb057e1a0826e4683"

[[releases]]
version = "10.5.1"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v10.5.1.tar.gz"
etag = "0cca0abd17032c3cfe809317f5cfda0d"

[[releases]]
version = "10.5.2"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v10.5.2.tar.gz"
etag = "f9ea999d4ffb534585478f2a12ced89d"

[[releases]]
version = "10.6.0"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v10.6.0.tar.gz"
etag = "729425e7871ab09afb7f4b29ff129e5b"

[[releases]]
version = "10.7.0"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v10.7.0.tar.gz"
etag = "db01f8605e1ba4fa231444c2d118f043"

[[releases]]
version = "10.8.0"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v10.8.0.tar.gz"
etag = "cefdbbfb99bb51f51289bb658202d662"

[[releases]]
version = "10.8.1"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v10.8.1.tar.gz"
etag = "e1f50d50ee8bf60a68b05faed7b0aa54"

[[releases]]
version = "10.8.2"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v10.8.2.tar.gz"
etag = "c38dba0d2844e46ef5934baceb09f05f"

[[releases]]
version = "10.8.3"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v10.8.3.tar.gz"
etag = "771e1ec16188cf1e6f613b03842bc452"

[[releases]]
version = "10.9.0"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v10.9.0.tar.gz"
etag = "9786e0277c6f084d7fbcdabf6ddb052a"

[[releases]]
version = "10.9.1"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v10.9.1.tar.gz"
etag = "f0cc6a619daaf925736752a904e6ac7a"

[[releases]]
version = "10.9.2"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v10.9.2.tar.gz"
etag = "f207e154ceb4d648839ef80ff6b1800a"

[[releases]]
version = "11.0.0"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v11.0.0.tar.gz"
etag = "3b77b99ab7166d31d415fdcc70a836f9"

[[releases]]
version = "11.1.0"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v11.1.0.tar.gz"
etag = "00c678e15bd147e8b8a2fdfe9b9de5aa"

[[releases]]
version = "8.0.0"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v8.0.0.tar.gz"
etag = "f57e5811cb6e26d00b8b06e1eea67c65"

[[releases]]
version = "8.1.0"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v8.1.0.tar.gz"
etag = "0a29c338adba902749b7bb265007bab9"

[[releases]]
version = "8.1.1"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v8.1.1.tar.gz"
etag = "5996c416396cdd330ddc3a7540a1f18d"

[[releases]]
version = "8.1.2"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v8.1.2.tar.gz"
etag = "6c5b07cc8552123ec82e7403fe1e2f0f"

[[releases]]
version = "8.1.3"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v8.1.3.tar.gz"
etag = "83e60269c91ed4606161b9803dd9ed30"

[[releases]]
version = "8.1.4"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v8.1.4.tar.gz"
etag = "be0df53c851b31d4d507a4bcd8689933"

[[releases]]
version = "8.10.0"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v8.10.0.tar.gz"
etag = "325b552c2ed890aef120fa4d13292114"

[[releases]]
version = "8.11.0"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v8.11.0.tar.gz"
etag = "2c3c661e95ef0503816fb0319c152093"

[[releases]]
version = "8.12.0"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v8.12.0.tar.gz"
etag = "576b8b3f3c082fd4316b8e1ab9e73c74"

[[releases]]
version = "8.12.1"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v8.12.1.tar.gz"
etag = "71d59274edd60f15c053d0236fdd2bbe"

[[releases]]
version = "8.12.2"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v8.12.2.tar.gz"
etag = "afcc70608c87a0583a325e9fe4281e25"

[[releases]]
version = "8.13.0"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v8.13.0.tar.gz"
etag = "2a6a6603fddb70939609bc933bb31f93"

[[releases]]
version = "8.13.1"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v8.13.1.tar.gz"
etag = "5e7e57ef4d8ac7ad6744716ae334bc93"

[[releases]]
version = "8.13.2"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v8.13.2.tar.gz"
etag = "4eb61d6ee6415c32f5ca360741c7024e"

[[releases]]
version = "8.14.0"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v8.14.0.tar.gz"
etag = "192c90ee0ecd40511685a7d3a568c33c"

[[releases]]
version = "8.15.0"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v8.15.0.tar.gz"
etag = "080f4eff8f327063315a273346edfd6d"

[[releases]]
version = "8.15.1"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v8.15.1.tar.gz"
etag = "c86616f24edef13b44faec0119ac65fe"

[[releases]]
version = "8.16.0"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v8.16.0.tar.gz"
etag = "ed13b9b1bc5259efa9460438a209246e"

[[releases]]
version = "8.17.0"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v8.17.0.tar.gz"
etag = "3a4dad8e78d927befbb77ae84a0773bd"

[[releases]]
version = "8.18.0"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v8.18.0.tar.gz"
etag = "4cc6097152a77bfdca8593f476c3db6a"

[[releases]]
version = "8.19.0"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v8.19.0.tar.gz"
etag = "f2658620f95443db7d317ee113493365"

[[releases]]
version = "8.19.1"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v8.19.1.tar.gz"
etag = "04159b834f76086fecd2337db3a3224d"

[[releases]]
version = "8.19.2"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v8.19.2.tar.gz"
etag = "886f933d3d8955ff150d713ae9725ba5"

[[releases]]
version = "8.19.3"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v8.19.3.tar.gz"
etag = "940c84adc0b2492c14c0375ff32cea6c"

[[releases]]
version = "8.19.4"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v8.19.4.tar.gz"
etag = "00cdcfb88101c64d910169a6d15e6aa2"

[[releases]]
version = "8.2.0"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v8.2.0.tar.gz"
etag = "b82219126d2f47e1f0fb668682b7aaeb"

[[releases]]
version = "8.3.0"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v8.3.0.tar.gz"
etag = "8a5be4f27f91629fa668b9b15e733fd6"

[[releases]]
version = "8.3.1"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v8.3.1.tar.gz"
etag = "927fad24c43cd064ae2e010d7886732d"

[[releases]]
version = "8.3.2"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v8.3.2.tar.gz"
etag = "878c74309efeabbd907fab935fe05bb3"

[[releases]]
version = "8.4.0"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v8.4.0.tar.gz"
etag = "e805e6dee82d4f70dfbb353e19917796"

[[releases]]
version = "8.4.1"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v8.4.1.tar.gz"
etag = "1ed8fc6340d71a12d105c4e7eacf68ae"

[[releases]]
version = "8.5.0"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v8.5.0.tar.gz"
etag = "fc2fe011afd17b09d0d5aaddac122888"

[[releases]]
version = "8.5.1"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v8.5.1.tar.gz"
etag = "5b4c9dcd3dfb70b3ae838a72f3336b9e"

[[releases]]
version = "8.5.2"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v8.5.2.tar.gz"
etag = "eef4c4e44a99510e0d21952a35b2fa12"

[[releases]]
version = "8.5.3"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v8.5.3.tar.gz"
etag = "adaee7af0c32997e1b10138b887b64d7"

[[releases]]
version = "8.5.4"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v8.5.4.tar.gz"
etag = "1ca70f32efea790d7d765da9fb0f945e"

[[releases]]
version = "8.5.5"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v8.5.5.tar.gz"
etag = "c3ea22c421f419c940daf6915025f7b1"

[[releases]]
version = "8.6.0"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v8.6.0.tar.gz"
etag = "50460002e456814fea3869bc23d3a343"

[[releases]]
version = "8.7.0"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v8.7.0.tar.gz"
etag = "fdd55021ab1efa755ded1decedc63149"

[[releases]]
version = "8.8.0"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v8.8.0.tar.gz"
etag = "60f5e3abea1cf0466116115e587f7b07"

[[releases]]
version = "8.9.0"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v8.9.0.tar.gz"
etag = "5befe879deb83adaa644be39a841251b"

[[releases]]
version = "9.0.0"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v9.0.0.tar.gz"
etag = "2afebf2e6192dc5dad60479e21be5e0a"

[[releases]]
version = "9.0.1"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v9.0.1.tar.gz"
etag = "ac1bf9cdea7a8027118e63d3ec719f4e"

[[releases]]
version = "9.1.0"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v9.1.0.tar.gz"
etag = "691433823562f183a0b4adb80aeb9e0c"

[[releases]]
version = "9.1.1"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v9.1.1.tar.gz"
etag = "18d7655ca1a6ca49e5303edddbe5ad14"

[[releases]]
version = "9.1.2"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v9.1.2.tar.gz"
etag = "be2bf5582ea3cf887ae11375b54254f6"

[[releases]]
version = "9.1.3"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v9.1.3.tar.gz"
etag = "f6d39cec10e75f8f61bb465f0e1964f2"

[[releases]]
version = "9.2.0"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v9.2.0.tar.gz"
etag = "1a1714da4d8169f2229be7c4457d38b1"

[[releases]]
version = "9.3.0"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v9.3.0.tar.gz"
etag = "0073b825084c551fa2d13420ab439e20"

[[releases]]
version = "9.3.1"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v9.3.1.tar.gz"
etag = "9a3e9f5d0c3357e68bf4810ecac0306b"

[[releases]]
version = "9.4.0"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v9.4.0.tar.gz"
etag = "40af9283db14b4f01ab6c81677dd7221"

[[releases]]
version = "9.4.1"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v9.4.1.tar.gz"
etag = "1f7d00ce4e2ea14f75b9d70677185145"

[[releases]]
version = "9.4.2"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v9.4.2.tar.gz"
etag = "f07e73bf710cc6f0b79ef978d1fadb13"

[[releases]]
version = "9.5.0"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v9.5.0.tar.gz"
etag = "2dc0b3d652470c78eba35ce6edc82454"

[[releases]]
version = "9.5.1"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v9.5.1.tar.gz"
etag = "58e994784a937c1afd392b9ada600822"

[[releases]]
version = "9.6.0"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v9.6.0.tar.gz"
etag = "a70bfe639f48f24e72385b24fe33492a"

[[releases]]
version = "9.6.1"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v9.6.1.tar.gz"
etag = "445470c705ba61da5da3742fe02528bf"

[[releases]]
version = "9.6.2"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v9.6.2.tar.gz"
etag = "f8c27527296077334574f98c99330d89"

[[releases]]
version = "9.6.3"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v9.6.3.tar.gz"
etag = "9ccac52b1e317d0a23759ff7f8200b01"

[[releases]]
version = "9.6.4"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v9.6.4.tar.gz"
etag = "7f6a72bf960610de1c905ade67bc0dc7"

[[releases]]
version = "9.6.5"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v9.6.5.tar.gz"
etag = "b3458928f6d50aede583b8002ec25814"

[[releases]]
version = "9.6.6"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v9.6.6.tar.gz"
etag = "aebff29bee406bcc491573f00106edd2"

[[releases]]
version = "9.6.7"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v9.6.7.tar.gz"
etag = "b85f34d64a8224a25221c5b57b8a29e5"

[[releases]]
version = "9.7.0"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v9.7.0.tar.gz"
etag = "290bb0fc344dd0da80732d7703d3614a"

[[releases]]
version = "9.7.1"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v9.7.1.tar.gz"
etag = "aaa52932b8cf3ccad629f9e14ca39ad2"

[[releases]]
version = "9.7.2"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v9.7.2.tar.gz"
etag = "10d35fb2b79993038464ce698ec0d2c5"

[[releases]]
version = "9.8.0"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v9.8.0.tar.gz"
etag = "f7d03233261854ef783504dfbb103f23"

[[releases]]
version = "9.8.1"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v9.8.1.tar.gz"
etag = "a54b82af3b9133e8d9a4825ee04bbbb1"

[[releases]]
version = "9.9.0"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v9.9.0.tar.gz"
etag = "7abb5e63930fba210e2567f2d61a04c6"

[[releases]]
version = "9.9.1"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v9.9.1.tar.gz"
etag = "a128a47efd7ca009180d0e25838796cd"

[[releases]]
version = "9.9.2"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v9.9.2.tar.gz"
etag = "aff03aeb0edaf8121bd0268db088d101"

[[releases]]
version = "9.9.3"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v9.9.3.tar.gz"
etag = "593b08cbb00bd0ddbd22fa87b3e199fc"

[[releases]]
version = "9.9.4"
channel = "release"
url = "https://heroku-nodebin.s3.us-east-1.amazonaws.com/npm/release/npm-v9.9.4.tar.gz"
etag = "ea6a0a035d0d1b9d6e9d6798d2081211"

