api = "0.9"

[buildpack]
id = "heroku/nodejs-corepack"
version = "1.1.5"
name = "Heroku Node.js Corepack"
homepage = "https://github.com/heroku/buildpacks-nodejs"
keywords = ["corepack", "node", "node.js", "nodejs", "javascript", "js"]

[[buildpack.licenses]]
type = "MIT"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "heroku-22"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[metadata]
[metadata.release]
[metadata.release.image]
repository = "docker.io/heroku/buildpack-nodejs-corepack"
