api = "0.10"

[buildpack]
id = "heroku/nodejs-corepack"
version = "3.0.4"
name = "Heroku Node.js Corepack"
homepage = "https://github.com/heroku/buildpacks-nodejs"
description = "Heroku's Node.js Corepack buildpack. A component of the 'heroku/nodejs' buildpack."
keywords = ["corepack", "heroku"]

[[buildpack.licenses]]
type = "MIT"

[[stacks]]
id = "*"

[[targets]]
os = "linux"
arch = "amd64"

[metadata.release]
image = { repository = "docker.io/heroku/buildpack-nodejs-corepack" }
