api = "0.9"

[buildpack]
id = "heroku/nodejs-corepack"
version = "2.6.1"
name = "Heroku Node.js Corepack"
homepage = "https://github.com/heroku/buildpacks-nodejs"
description = "Heroku's Node.js Corepack buildpack. A component of the 'heroku/nodejs' buildpack."
keywords = ["corepack", "heroku"]

[[buildpack.licenses]]
type = "MIT"

[[stacks]]
id = "*"

[metadata.release]
image = { repository = "docker.io/heroku/buildpack-nodejs-corepack" }
