api = "0.9"

[buildpack]
id = "heroku/nodejs-engine"
version = "2.6.4"
name = "Heroku Node.js Engine"
homepage = "https://github.com/heroku/buildpacks-nodejs"
description = "Heroku's Node.js engine buildpack. A component of the 'heroku/nodejs' buildpack."
keywords = ["node.js", "nodejs", "heroku"]

[[buildpack.licenses]]
type = "MIT"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "heroku-22"

[metadata.release]
image = { repository = "docker.io/heroku/buildpack-nodejs-engine" }
