api = "0.10"

[buildpack]
id = "heroku/nodejs-engine"
version = "3.2.2"
name = "Heroku Node.js Engine"
homepage = "https://github.com/heroku/buildpacks-nodejs"
description = "Heroku's Node.js engine buildpack. A component of the 'heroku/nodejs' buildpack."
keywords = ["node.js", "nodejs", "heroku"]

[[buildpack.licenses]]
type = "MIT"

[[stacks]]
id = "*"

[[targets]]
os = "linux"
arch = "amd64"

[[targets]]
os = "linux"
arch = "arm64"

[metadata.release]
image = { repository = "docker.io/heroku/buildpack-nodejs-engine" }
