api = "0.10"

[buildpack]
id = "heroku/nodejs-npm-engine"
version = "3.2.15"
name = "Heroku Node.js npm Engine"
homepage = "https://github.com/heroku/buildpacks-nodejs"
description = "Heroku's Node.js npm engine buildpack. A component of the 'heroku/nodejs' buildpack."
keywords = ["npm", "heroku"]

[[buildpack.licenses]]
type = "MIT"

[[stacks]]
id = "*"

[[targets]]
os = "linux"
arch = "amd64"

[[targets]]
os = "linux"
arch = "arm64"

[metadata.release]
image = { repository = "docker.io/heroku/buildpack-nodejs-npm-engine" }
