unit-test-heroku-20:
	@docker run -v $(PWD):/project danielleadams/shpec:latest

unit-test-heroku-18:
	@docker run -v $(PWD):/project danielleadams/shpec-heroku-18:latest

unit-test-heroku-16:
	@docker run -v $(PWD):/project danielleadams/shpec-heroku-16:latest

docker-unit-test:
	@docker run -v $(PWD):/project danielleadams/shpec:latest
