api = "0.9"

[buildpack]
id = "heroku/nodejs-yarn"
version = "2.4.0"
name = "Heroku Node.js Yarn"
homepage = "https://github.com/heroku/buildpacks-nodejs"
description = "Heroku's Node.js Yarn buildpack. A component of the 'heroku/nodejs' buildpack."
keywords = ["yarn", "heroku"]

[[buildpack.licenses]]
type = "MIT"

[[stacks]]
id = "*"

[metadata.release]
image = { repository = "docker.io/heroku/buildpack-nodejs-yarn" }
