api = "0.10"

[buildpack]
id = "heroku/nodejs-yarn"
version = "4.1.4"
name = "Heroku Node.js Yarn"
homepage = "https://github.com/heroku/buildpacks-nodejs"
description = "Heroku's Node.js Yarn buildpack. A component of the 'heroku/nodejs' buildpack."
keywords = ["yarn", "heroku"]

[[buildpack.licenses]]
type = "MIT"

[[stacks]]
id = "*"

[[targets]]
os = "linux"
arch = "amd64"

[[targets]]
os = "linux"
arch = "arm64"

[metadata.release]
image = { repository = "docker.io/heroku/buildpack-nodejs-yarn" }
