api = "0.9"

[buildpack]
id = "heroku/nodejs-yarn"
version = "1.1.3"
name = "Heroku Node.js Yarn"
homepage = "https://github.com/heroku/buildpacks-nodejs"
keywords = ["node", "node.js", "nodejs", "javascript", "js", "yarn", "yarnpkg"]

[[buildpack.licenses]]
type = "MIT"

[[stacks]]
id = "*"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "heroku-22"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[metadata]
[metadata.release]
[metadata.release.docker]
repository = "docker.io/heroku/buildpack-nodejs-yarn"
