api = "0.9"

[buildpack]
id = "heroku/nodejs-yarn"
version = "1.1.7"
name = "Heroku Node.js Yarn"
homepage = "https://github.com/heroku/buildpacks-nodejs"
description = "Heroku's Node.js Yarn buildpack. A component of the 'heroku/nodejs' buildpack."
keywords = ["yarn", "heroku"]

[[buildpack.licenses]]
type = "MIT"

[[stacks]]
id = "*"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "heroku-22"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[metadata.release]
image = { repository = "docker.io/heroku/buildpack-nodejs-yarn" }
