name: CI

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read

jobs:
  rust-lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Update Rust toolchain
        run: rustup update

      - name: Rust Cache
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - name: Clippy
        run: cargo clippy --all-targets --workspace --locked -- --deny warnings

      - name: rustfmt
        run: cargo fmt -- --check

  rust-unit-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Update Rust toolchain
        run: rustup update

      - name: Rust Cache
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - name: Run unit tests
        run: cargo test --locked

  rust-integration-test:
    name: Integration (${{ matrix.builder }}, ${{ matrix.arch }})
    runs-on: ${{ matrix.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}

    env:
      INTEGRATION_TEST_CNB_BUILDER: heroku/${{ matrix.builder }}

    strategy:
      fail-fast: false
      matrix:
        builder: ["builder:26", "builder:24", "builder:22"]
        arch: ["amd64", "arm64"]
        exclude:
          - builder: "builder:22"
            arch: "arm64"

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Disable containerd snapshotter feature
        run: |
          docker info -f '{{ .DriverStatus }}'
          sudo systemctl stop docker
          echo '{"features": {"containerd-snapshotter": false}}' | sudo tee /etc/docker/daemon.json
          sudo systemctl start docker
          docker info -f '{{ .DriverStatus }}'

      # The dpkg man-db trigger is excessively slow on GHA runners, see e.g.:
      # https://github.com/actions/runner-images/issues/10977
      # https://github.com/actions/runner/issues/4030
      # We disable it here so it does not fire at the end of the following apt-get install
      - name: Disable man-db auto-update
        run: sudo rm -f /var/lib/man-db/auto-update

      - name: Install musl-tools
        run: sudo apt-get install musl-tools -y --no-install-recommends

      - name: Update Rust toolchain
        run: rustup update

      - name: Install Rust linux-musl target
        run: rustup target add ${{ matrix.arch == 'arm64' && 'aarch64-unknown-linux-musl' || 'x86_64-unknown-linux-musl' }}

      - name: Rust Cache
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - name: Install Pack CLI
        uses: buildpacks/github-actions/setup-pack@b4faaabcd9dbc5fa332451ae33bce8b583f3ec1b # v5.12.0

      - name: Install Nextest
        uses: taiki-e/install-action@7769b73c2ec98c38dfcf2e18c83cfd4880c038c1 # v2.75.27
        with:
          tool: nextest

      - name: Pull builder image
        run: docker pull ${{ env.INTEGRATION_TEST_CNB_BUILDER }}

      - name: Pull run image
        run: |
          RUN_IMAGE=$(
            docker inspect --format='{{index .Config.Labels "io.buildpacks.builder.metadata"}}' '${{ env.INTEGRATION_TEST_CNB_BUILDER }}' \
            | jq --exit-status --raw-output '.stack.runImage.image'
          )
          docker pull "${RUN_IMAGE}"

      - name: Run integration tests
        run: cargo nextest run --run-ignored only --locked
