name: Mirror Node.js Distribution
on:
  workflow_call:
    inputs:
      version:
        description: "The Node.js version to mirror"
        required: true
        type: string
      platform:
        description: "The platform target to mirror"
        default: "linux-x64"
        required: true
        type: string

jobs:
  mirror_node:
    runs-on: sfdc-hk-ubuntu-22.04-medium
    steps:
      - name: Checkout nodebin
        uses: actions/checkout@v3

      - name: Download Node.js distribution and verification files
        run: common/bin/download-node "${{ inputs.version }}" "${{ inputs.platform }}"

      - name: Verify Node.js distribution
        run: common/bin/verify-node "${{ inputs.version }}" "${{ inputs.platform}}"

      - name: Upload Node.js distribution to staging S3 bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: >
          aws s3 cp
          "node-v${{ inputs.version }}-${{ inputs.platform }}.tar.gz"
          "s3://${{ secrets.AWS_S3_BUCKET }}/node/staging/${{ inputs.platform}}/node-v${{ inputs.version }}-${{ inputs.platform }}.tar.gz"

      - name: Copy Node.js distribution to release folder in S3 bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: >
          aws s3 cp
          --copy-props none
          "s3://${{ secrets.AWS_S3_BUCKET }}/node/staging/${{ inputs.platform }}/node-v${{ inputs.version }}-${{ inputs.platform }}.tar.gz"
          "s3://${{ secrets.AWS_S3_BUCKET }}/node/release/${{ inputs.platform }}/node-v${{ inputs.version }}-${{ inputs.platform }}.tar.gz"

      - name: Send success notification
        env:
          SHURIKEN_USER: ${{ secrets.SHURIKEN_USER }}
          SHURIKEN_TOKEN: ${{ secrets.SHURIKEN_TOKEN }}
          SHURIKEN_CHANNEL: ${{ secrets.SHURIKEN_CHANNEL }}
        run: >
          common/bin/notify-shuriken
          "Node.js ${{ inputs.version }} distribution for ${{ inputs.platform }} mirror to S3 *succeeded*."
          "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          "#68f442"

      - name: Send failure notification
        if: failure() && !cancelled()
        env:
          SHURIKEN_USER: ${{ secrets.SHURIKEN_USER }}
          SHURIKEN_TOKEN: ${{ secrets.SHURIKEN_TOKEN }}
          SHURIKEN_CHANNEL: ${{ secrets.SHURIKEN_CHANNEL }}
        run: >
          common/bin/notify-shuriken
          "Node.js ${{ inputs.version }} binary for ${{ inputs.platform }} release to S3 *failed*."
          "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          "#f44141"

